<?php

use Illuminate\Database\Seeder;

class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('municipios')->insert([
            ['nome'=>'Alvarães',
                "regionals_id"=>7],
            ["nome"=>'Amaturá',
                "regionals_id"=>1],
            ["nome"=>'Anamã',
                "regionals_id"=>3],
            ["nome"=>'Anori',
                "regionals_id"=>3],
            ["nome"=>'Apuí',
                "regionals_id"=>8],
            ["nome"=>'Atalaia do Norte',
                "regionals_id"=>1],
            ["nome"=>'Autazes',
                "regionals_id"=>4],
            ["nome"=>'Barcelos',
                "regionals_id"=>4],
            ["nome"=>'Barreirinha',
                "regionals_id"=>5],
            ["nome"=>'Benjamin Constant',
                "regionals_id"=>1],
            ["nome"=>'Beruri',
                "regionals_id"=>3],
            ["nome"=>'Boa Vista do Ramos',
                "regionals_id"=>5],
            ["nome"=>'Boca do Acre',
                "regionals_id"=>6],
            ["nome"=>'Borba',
                "regionals_id"=>8],
            ["nome"=>'Caapiranga',
                "regionals_id"=>3],
            ["nome"=>'Canutama',
                "regionals_id"=>6],
            ["nome"=>'Carauari',
                "regionals_id"=>9],
            ["nome"=>'Careiro Castanho',
                "regionals_id"=>4],
            ["nome"=>'Careiro da Várzea',
                "regionals_id"=>4],
            ["nome"=>'Coari',
                "regionals_id"=>3],
            ["nome"=>'Codajás',
                "regionals_id"=>3],
            ["nome"=>'Eirunepé',
                "regionals_id"=>9],
            ["nome"=>'Envira',
                "regionals_id"=>9],
            ["nome"=>'Fonte Boa',
                "regionals_id"=>1],
            ["nome"=>'Guajará',
                "regionals_id"=>9],
            ["nome"=>'Humaitá',
                "regionals_id"=>8],
            ["nome"=>'Ipixuna',
                "regionals_id"=>9],
            ["nome"=>'Iranduba',
                "regionals_id"=>4],
            ["nome"=>'Itacoatiara',
                "regionals_id"=>2],
            ["nome"=>'Itamarati',
                "regionals_id"=>9],
            ["nome"=>'Itapiranga',
                "regionals_id"=>2],
            ["nome"=>'Japurá',
                "regionals_id"=>7],
            ["nome"=>'Juruá',
                "regionals_id"=>7],
            ["nome"=>'Jutaí',
                "regionals_id"=>1],
            ["nome"=>'Lábrea',
                "regionals_id"=>6],
            ["nome"=>'Manacapuru',
                "regionals_id"=>3],
            ["nome"=>'Manaquiri',
                "regionals_id"=>4],
            ["nome"=>'Manaus',
                "regionals_id"=>4],
            ["nome"=>'Manicoré',
                "regionals_id"=>8],
            ["nome"=>'Maraã',
                "regionals_id"=>7],
            ["nome"=>'Maués',
                "regionals_id"=>5],
            ["nome"=>'Nhamundá',
                "regionals_id"=>5],
            ["nome"=>'Nova Olinda do Norte',
                "regionals_id"=>4],
            ["nome"=>'Novo Airão',
                "regionals_id"=>3],
            ["nome"=>'Novo Aripuanã',
                "regionals_id"=>8],
            ["nome"=>'Parintins',
                "regionals_id"=>5],
            ["nome"=>'Pauini',
                "regionals_id"=>6],
            ["nome"=>'Presidente Figueiredo',
                "regionals_id"=>4],
            ["nome"=>'Rio Preto da Eva',
                "regionals_id"=>4],
            ["nome"=>'Santa Isabel do Rio Negro',
                "regionals_id"=>4],
            ["nome"=>'Santo Antônio do Içá',
                "regionals_id"=>1],
            ["nome"=>'Silves',
                "regionals_id"=>2],
            ["nome"=>'São Gabriel da Cachoeira',
                "regionals_id"=>4],
            ["nome"=>'São Paulo de Olivença',
                "regionals"=>1],
            ["nome"=>'São Sebastião do Uatumã',
                "regionals_id"=>2],
            ["nome"=>'Tabatinga',
                "regionals_id"=>1],
            ["nome"=>'Tapauá',
                "regionals_id"=>6],
            ["nome"=>'Tefé',
                "regionals_id"=>7],
            ["nome"=>'Tonantins',
                "regionals_id"=>1],
            ["nome"=>'Uarini',
                "regionals_id"=>7],
            ["nome"=>'Urucará',
                "regionals_id"=>2],
            ["nome"=>'Urucurituba',
                "regionals_id"=>2]
        ]);
    }
}
